[font]
size = 11
normal = { family = "Iosevka Nerd Font", style = "regular" }
offset = { x = -1, y = -1 }

[window]
padding = { x = 10, y = 15 } 
dynamic_title = true

[colors.primary]
background = "#090917"
foreground = "#b3b1ad"
